### ISSUE TITLE
Transfer /search-playground to docs.mapbox.com

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/search-playground#27]
@mapbox/frontend-platform and @mapbox/docs are working together to transfer this site to the new `docs.mapbox.com` domain.

Here are the steps in the process.

- [x] Launch the staging site at `docs.tilestream.net`.
- [x] QA the staging site .
- [x] Launch the production site at `docs.mapbox.com`.
- [x] 301 redirect from `www` to `docs`.
- [ ] Delete `www` files and branches.

We're going to start on this today, and try to finish it today or tomorrow.

**Comment by davidtheclark** [comment]
This is now live on staging at https://docs.tilestream.net/search-playground. Can @mapbox/docs & @mapbox/search please take a look at the staging site and verify that it's working as expected?

**Comment by katydecorah** [comment]
@davidtheclark This appears to me to be working as expected.

**Comment by ingalls** [comment]
@davidtheclark Sweet, only gotcha to be aware of (and it may not be a gotcha) is this is intentionally simultaneously deployed to both mapbox.com (public facing) and hey.mapbox.com (dev facing). Although the code is the same, the hey.mapbox.com as access to resources only avaliable via private-proxy so we want to ensure this stays deployed and accessible.

**Comment by davidtheclark** [comment]
Public site is now live at https://docs.mapbox.com/search-playground. Redirects coming soon.

**Comment by davidtheclark** [comment]
The transition is complete!

Last step is to delete the old `*-pages` pages and switch the main branch. @katydecorah or @ingalls, whoever has permission, could you please finish that up and then close this issue?
