### ISSUE TITLE
center map to the queried location in case the query is opened from a url

### ISSUE THREAD

**Issue by udos** [mapbox/search-playground#40]
it would be really useful if the map would center itself on the queried location when opening a link like https://docs.mapbox.com/search-playground/#{"query":"7.674619865262457,44.11822281893441"}

currently when opening the page via a link it always centers here:
![image](https://user-images.githubusercontent.com/141107/59846110-4c224000-935f-11e9-90ae-91e600fb9826.png)

**Comment by ingalls** [comment]
@udos Good call, thanks a ton for reporting, this has been a personal pet peeve of mine but just haven't gotten a chance to tackle it. Will add it to the backlog. (We're also always happy to accept PRs if you get to it ahead of us!)
