### ISSUE TITLE
Geocoding autocomplete search doesn't display/show any Argentine addresses

### ISSUE THREAD

**Issue by Iann7** [mapbox/search-playground#42]
I know that I should report issues related to seach resource through https://labs.mapbox.com/geocoder-feedback/ but the issue seemed really important and I thought that I should post it here.

It seems like Argentine addresses are not displayed to the user if the user is searching a street located in Argentina 

Photo of the geocoding playground :

(https://user-images.githubusercontent.com/48655321/62747326-4de8b580-ba2a-11e9-81ab-31b4343f065b.png)

**Comment by ingalls** [comment]
@Iann7 Thanks for reaching out. I'm afraid at the moment the Mapbox Geocoding Service does not support Argentinian addresses. We would love to add support in the future but don't currently have a timeline for this coverage.
